GET http://localhost:3001/api/member/list HTTP/1.1
Content-Type: application/json
###
POST http://localhost:3001/api/member/create HTTP/1.1
Content-Type: application/json

{
    "firstname":"Tamene",
    "lastname":"Binchamo",
    "middlename":"Demissie",
    "sex":"Male",
    "age":"30"
}
###
DELETE  http://localhost:3001/api/member/remove HTTP/1.1
Content-Type: application/json

{
    "firstname":"Tamene",
    "lastname":"Binchamo",
    "middlename":"Demissie"
}
###
DELETE  http://localhost:3001/api/member/remove?id=62b8a14cc20dfbf1055db210 HTTP/1.1
Content-Type: application/json


###
PUT  http://localhost:3001/api/member/update?id=62b8a1f5c20dfbf1055db21d HTTP/1.1
Content-Type: application/json

{
    "age": 31
}